### ISSUE TITLE
AWS Lambda custom runtime with native-image fails with "Unconvertible input: null"

### ISSUE THREAD

**Issue by wololock** [micronaut-projects/micronaut-aws#465]
Hello, Micronaut Team! I'm trying to deploy AWS Lambda using a native-image function generated with GraalVM. I tried the demo `BookLambdaRuntime` with the same result. (Running AWS Lambda from the JAR with the same application works without any issues.) I don't know if I make some trivial mistake, or if there is some bug in the latest Micronaut 2.x, so I decided to let you know about it.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

```
$ mn create-function-app --jdk=11 com.github.wololock.function-example -f graalvm,aws-lambda,http-client

$ cd function-example/

$ ./docker-build.sh

$ ./deploy.sh
```

I take the `build/function.zip` file and I upload it to the AWS Lambda `new-function` I created.

Here are AWS Lambda runtime settings for that function.

![Przechwycenie obrazu ekranu_2020-08-24_19-16-32](https://user-images.githubusercontent.com/1258405/91075455-60865a80-e63e-11ea-91dc-ed88fb96e006.png)

I run the test with the simple input:

```
{
  "name": "Micronaut In Action"
}
```

Running the test causes the following error:

```
START RequestId: e6f0ad2f-1fe7-4736-bc45-13b5451479fb Version: $LATEST
Invocation with requestId [e6f0ad2f-1fe7-4736-bc45-13b5451479fb] failed: Unconvertible input: nulljava.lang.IllegalArgumentException: Unconvertible input: null
	at io.micronaut.function.aws.MicronautRequestHandler.lambda$convertInput$0(MicronautRequestHandler.java:78)
	at java.util.Optional.orElseThrow(Optional.java:408)
	at io.micronaut.function.aws.MicronautRequestHandler.convertInput(MicronautRequestHandler.java:77)
	at io.micronaut.function.aws.MicronautRequestHandler.handleRequest(MicronautRequestHandler.java:59)
	at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.startRuntimeApiEventLoop(AbstractMicronautLambdaRuntime.java:347)
	at io.micronaut.function.aws.runtime.AbstractMicronautLambdaRuntime.run(AbstractMicronautLambdaRuntime.java:129)
	at com.github.wololock.BookLambdaRuntime.main(BookLambdaRuntime.java:13)
```

![Przechwycenie obrazu ekranu_2020-08-24_19-19-38](https://user-images.githubusercontent.com/1258405/91075720-c83ca580-e63e-11ea-977c-6303dd7c74da.png)

According to logs, the native image application starts, but the `MicronautRequestHandler` can't read the input I use for tests.

### Expected Behaviour

The demo function app should return the book's name and a random ISBN in a JSON response.

### Actual Behaviour

The demo function fails to read the input.

### Environment Information

- **Operating System**: AWS Lambda
- **Micronaut Version:** Micronaut 2.0.1
- **JDK Version:** Amazon Corretto 11

### Example Application

The application I use for testing comes from the default demo function app generated with the `mn` client. I haven't added any code.

**Comment by ilopmar** [comment]
@wololock We have a test application for AWS Function + GraalVM here: https://github.com/micronaut-graal-tests/micronaut-function-aws-graal

Please take a look at it and let me know if that works for you.

**Comment by wololock** [comment]
Thanks for the repo link, @ilopmar! :smile: 

I did a quick run - `./build-native-image.sh` + manual function upload using AWS Lambda UI, then running test with `{"category": "foo"}` and it fails on starting the native app:

![Przechwycenie obrazu ekranu_2020-08-24_23-31-44](https://user-images.githubusercontent.com/1258405/91098720-478fa080-e662-11ea-93da-c8c33f0fd901.png)

I'm gonna dig into that tomorrow, I'm guessing this might be a problem on my side with the function setup. I will use your CloudFormation template to make a complete deployment from the terminal and see how it works. 

I will share an update when I find something. Thanks!

**Comment by ilopmar** [comment]
Thanks. Our CI passes [build](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/701185207) and [test](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/701185325) but we are using now GraalVM 20.3-dev and not 20.2.0 (which I assume you are using). I think I did try this with that version, but I might be wrong.

I've done a couple of quick tests deploying the function with the CloudFormation template and using both GraalVM 20.2.0 JDK8 & JDK11. It works in both cases. Just keep in mind that you need to remove `--install-exit-handlers` (https://github.com/micronaut-graal-tests/micronaut-function-aws-graal/blob/master/src/main/resources/META-INF/native-image/example.micronaut/function-application/native-image.properties#L3) because that is not working on 20.2.0. It was fixed a couple of weeks ago and it didn't make it to the 20.2.0 version (see https://github.com/oracle/graal/issues/2742)

**Comment by wololock** [comment]
@ilopmar, with a small delay, but I finally tested the program with a similar CloudFormation template as https://github.com/micronaut-graal-tests/micronaut-function-aws-graal/blob/master/sam-native.yaml This works fine, however it accesses the native image function using API Gateway. The test I was running previously did not involve API Gateway but rather testing AWS Lambda directly with the tool that AWS provides on the function page. I checked the function deployed with this template and running lambda function test fails with the same `java.lang.IllegalArgumentException: Unconvertible input: null`.

I don't know, maybe this is AWS Lambda internal issue or something, but the current state is the following:

- [x] Deploying Micronaut 2.x demo function as JAR and testing AWS Lambda on-site = **works** :heavy_check_mark: 
- [x] Deploying Micronaut 2.x demo function as a native-image using CloudFormation template and testing API Gateway = **works** :heavy_check_mark: 
- [ ] Deploying Micronaut 2.x demo function as a native-image and testing AWS Lambda on-site = **fails** :warning: 

Using API Gateway to access AWS Lambda is something I'm going to use anyway. However, I don't know if this issue affects using native-image AWS Lambda functions with a different type of trigger.

**Comment by sdelamo** [comment]
I have update the [Lambda documentation](https://micronaut-projects.github.io/micronaut-aws/latest/guide/index.html#lambda). There are multiple guides also linked from the documentation. 

I you are using a runtime such as`BookLambdaRuntime`, it expects the event received by the lambda to be a aws proxy event. Which is what you will receive if the lambda is triggered by API Gateway. 

I have include a example in the guide where I modify such an event. 

https://guides.micronaut.io/mn-serverless-function-aws-lambda-graalvm/guide/index.html#test

**Comment by sdelamo** [comment]
If you want to trigger your via S3 event, then you will need to update the Runtime class accordingly.

**Comment by wololock** [comment]
Awesome, that makes much more sense now, thanks @sdelamo! Feel free to close this issue, I think there is nothing to do. Thanks for your patience and willingness to explain how to use AWS Lambda with the Micronaut function app correctly, @ilopmar and @sdelamo :+1:
